### ISSUE TITLE
Manage the github forks for better navigation 

### ISSUE THREAD

**Issue by muddlebee** [cryptoShire/project-management#10]
@randomishwalk has collated and forked cool projects. Need a way to manage the upcoming forks and present in a productive way.

**Comment by muddlebee** [comment]
Going forward all the resources to be added here https://github.com/cryptoShire/awesome-web3.0

**Comment by randomishwalk** [comment]
Great thanks @muddlebee ! Will do

**Comment by muddlebee** [comment]
Closing this @randomishwalk in favour of #2  and taking this to done.

Yay 🚀  🥳  . First task closed. Cheeers 🍺
